#!/bin/bash

# jwatch by Rafał Pocztarski
# https://github.com/rsp/ppj

n=$1
l=0
f=$n.java

echo -e "\njwatch - https://github.com/rsp/ppj"

if [ -z "$n" ]
then
cat << 'end'

Usage: jwatch ClassName

jwatch creates a new Java class with empty main() if none exists
and then watches for changes, compiles and runs the code.

end
exit 1
fi

if [ ! -f $n.java ]
then
cat << 'end' | sed "s/Tmpl/$n/g" >> $f

public class Tmpl {

    public static void main(String[] args) {

        System.out.println();

    }

}

end
fi

command -v subl >/dev/null 2>&1 && subl $f

while true;
do
    m=`date +%s -r $f`
    if [ $m -ne $l ]; then
        echo -e '\n========================================================================\n'
        javac $f && java $n
    fi
    l=$m
    sleep 1
done

